apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 3.5.0
version: 6.16.6-bb.4
home: https://grafana.com/loki
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
  - name: unguiculus
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Promtail: v3.5.0
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find upstream chart's release notes and CHANGELOG here](https://github.com/grafana/helm-charts/releases?q=promtail&expanded=true)
    - [Find upstream application's release notes and CHANGELOG here](https://grafana.com/docs/loki/latest/release-notes/)
  helm.sh/images: |
    - name: promtail
      image: registry1.dso.mil/ironbank/opensource/grafana/promtail:v3.5.0
