apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: v2.4.2
version: 3.11.0-bb.1
home: https://grafana.com/loki
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
  - name: unguiculus
annotations:
  bigbang.dev/applicationVersions: |
    - Promtail: v2.4.2
