apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: v2.8.1
version: 6.11.0-bb.1
home: https://grafana.com/loki
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
  - name: unguiculus
annotations:
  bigbang.dev/applicationVersions: |
    - Promtail: v2.8.1
  helm.sh/images: |
    - name: promtail
      image: registry1.dso.mil/ironbank/opensource/grafana/promtail:v2.8.1
