{{- if .Values.istio.enabled  }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "promtail.selectorLabels" . | nindent 6 }}
{{- end }}
